#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$DIR"

MACHINE="$1"

if [ -z "$MACHINE" ]; then
  echo "Machine name is missing" 1>&2
  echo "Machines:" 1>&2
  echo "$(find $DIR/meta-opi/conf/machine/ -name *.conf  -type f -printf "%f\n" | cut -f 1 -d '.')" 1>&2
else
  BUILD_DIR="$DIR/build"

  # Create build environment
  . "$DIR/poky/oe-init-build-env" "$BUILD_DIR" > /dev/null
  if [ "$?" -eq 0 ]; then
    # Add machine and distro
    echo '' >> "$BUILD_DIR/conf/local.conf"
    sed -i '/# OPI/,$d' "$BUILD_DIR/conf/local.conf"
    echo '# OPI
MACHINE = "'"$MACHINE"'"
DISTRO = "opi"' >> "$BUILD_DIR/conf/local.conf"

    # Add layers
    echo '' >> "$BUILD_DIR/conf/bblayers.conf"
    sed -i '/# OPI/,$d' "$BUILD_DIR/conf/bblayers.conf"
    echo "# OPI
BBLAYERS += \" \\
  $DIR/meta-openembedded/meta-oe \\
  $DIR/meta-qt5 \\
  $DIR/meta-opi \\
  \"" >> "$BUILD_DIR/conf/bblayers.conf"

    echo "Run 'bitbake <target>'"
    echo "Images:"
    echo "$(find $DIR/meta-opi/recipes-core/images/ -name *.bb  -type f -printf "%f\n" | cut -f 1 -d '.')"
  fi
  unset BUILD_DIR
fi

unset DIR
